/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 19ac1613859417bbd2204ee402e765ed)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	SUBLYRA_EXTERNAL_LINKS_ENABLED: string;
	SUBLYRA_ADS_ENABLED: string;
	SUBLYRA_ADMIN_EMAILS: string;
	CLOUDFLARE_ACCESS_TEAM_DOMAIN: string;
	CLOUDFLARE_ACCESS_AUD: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUBLYRA_EXTERNAL_LINKS_ENABLED" | "SUBLYRA_ADS_ENABLED" | "SUBLYRA_ADMIN_EMAILS" | "CLOUDFLARE_ACCESS_TEAM_DOMAIN" | "CLOUDFLARE_ACCESS_AUD">> {}
}
