import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { ArrowLeft, Clock3, Download, Film, Globe2, Play, ShieldCheck, Star, UserRound } from 'lucide-react';
import { movies } from '../../../lib/movies';
import { getPublishedMovie } from '../../../db';
import { resolveOutboundDestination } from '../../../lib/security/outbound-links';
import { getRuntimeControls } from '../../../lib/security/runtime-controls';

export function generateStaticParams() { return movies.map((movie) => ({ slug: movie.slug })); }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const movie = await getPublishedMovie((await params).slug);
  if (!movie) return { title: 'Film not found — Sublyra' };
  const description = `${movie.tagline} Explore ${movie.title}, cast, rating, and ${movie.languages.length} subtitle languages on Sublyra.`;
  return { title: `${movie.title} — Sublyra`, description, openGraph: { title: `${movie.title} — Sublyra`, description, images: [{ url: movie.backdrop, alt: `${movie.title} cinematic artwork` }] }, twitter: { card: 'summary_large_image', title: `${movie.title} — Sublyra`, description, images: [movie.backdrop] } };
}

export default async function MoviePage({ params }: { params: Promise<{ slug: string }> }) {
  const movie = await getPublishedMovie((await params).slug);
  if (!movie) notFound();
  const controls = getRuntimeControls();
  const watchAvailable = resolveOutboundDestination(movie, 'watch', controls).ok;
  const telegramAvailable = resolveOutboundDestination(movie, 'telegram', controls).ok;
  return <main className="min-h-screen bg-[#171815] text-white">
    <section className="relative min-h-[720px] overflow-hidden"><img src={movie.backdrop} alt="" className="absolute inset-0 h-full w-full object-cover opacity-55"/><div className="absolute inset-0 bg-[linear-gradient(90deg,#171815_0%,rgba(23,24,21,.86)_42%,rgba(23,24,21,.18)_75%),linear-gradient(0deg,#171815_0%,transparent_55%)]"/><div className="relative mx-auto max-w-[1380px] px-5 pb-20 pt-8 sm:px-8 lg:px-12"><div className="flex items-center justify-between"><a href="/" className="flex items-center gap-2 text-sm text-white/65 hover:text-white"><ArrowLeft size={16}/> Back to collection</a><a href="/" className="font-serif text-2xl">Sublyra<span className="text-[#ef796d]">.</span></a></div><div className="grid min-h-[590px] items-end gap-10 pt-20 md:grid-cols-[250px_1fr] md:items-center"><img src={movie.poster} alt={`${movie.title} poster`} className="hidden aspect-[2/3] w-full object-cover shadow-2xl md:block"/><div className="max-w-3xl"><p className="mb-5 text-xs font-semibold uppercase tracking-[.22em] text-[#ef796d]">{movie.genre} · {movie.year}</p><h1 className="font-serif text-6xl leading-[.92] tracking-[-.055em] sm:text-8xl">{movie.title}</h1><p className="mt-5 font-serif text-xl italic text-white/55 sm:text-2xl">{movie.tagline}</p><div className="mt-7 flex flex-wrap gap-4 text-sm text-white/65"><span className="flex items-center gap-1.5"><Star size={15} className="fill-[#ef796d] text-[#ef796d]"/> {movie.rating}</span><span className="flex items-center gap-1.5"><Clock3 size={15}/>{movie.runtime}</span><span className="flex items-center gap-1.5"><Globe2 size={15}/>{movie.languages.length} subtitles</span></div><p className="mt-7 max-w-2xl leading-7 text-white/65">{movie.description}</p><div className="mt-8 flex flex-wrap gap-3">{watchAvailable ? <a href={`/out/${movie.slug}/watch`} rel="noopener noreferrer" className="flex items-center gap-2 rounded-full bg-[#ef796d] px-6 py-3.5 text-sm font-semibold"><Play size={17} fill="currentColor"/> Watch officially</a> : <span className="flex cursor-not-allowed items-center gap-2 rounded-full bg-white/10 px-6 py-3.5 text-sm text-white/45" title="Available only after rights verification"><Play size={17}/> Official link pending</span>}{telegramAvailable ? <a href={`/out/${movie.slug}/telegram`} rel="noopener noreferrer" className="flex items-center gap-2 rounded-full border border-white/20 px-6 py-3.5 text-sm font-semibold"><Download size={17}/> Open in Telegram</a> : <span className="flex cursor-not-allowed items-center gap-2 rounded-full border border-white/10 px-6 py-3.5 text-sm text-white/40" title="Available only after rights verification"><Download size={17}/> Telegram link pending</span>}</div><p className="mt-4 flex items-center gap-2 text-xs text-white/35"><ShieldCheck size={14}/> External links require current rights approval and an active safety switch.</p></div></div></div></section>

    <section className="mx-auto grid max-w-[1380px] gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_1fr] lg:px-12"><div><p className="section-kicker text-[#ef796d]">Film details</p><dl className="mt-7 divide-y divide-white/10 border-y border-white/10"><Detail icon={<Film size={16}/>} label="Release year" value={String(movie.year)}/><Detail icon={<Clock3 size={16}/>} label="Runtime" value={movie.runtime}/><Detail icon={<UserRound size={16}/>} label="Director" value={movie.director}/><Detail icon={<Globe2 size={16}/>} label="Subtitle count" value={`${movie.languages.length} languages`}/></dl><p className="mt-10 text-xs font-semibold uppercase tracking-[.18em] text-white/45">Cast</p><div className="mt-4 flex flex-wrap gap-2">{movie.cast.map((person) => <span key={person} className="rounded-full border border-white/10 px-4 py-2 text-sm text-white/65">{person}</span>)}</div></div><div><p className="section-kicker text-[#ef796d]">Available subtitles</p><div className="mt-7 flex flex-wrap gap-2">{movie.languages.map((language, index) => <span key={language} className="rounded-full bg-white/[.07] px-4 py-2.5 text-sm text-white/70"><span className="mr-2 text-xs text-white/25">{String(index + 1).padStart(2, '0')}</span>{language}</span>)}</div>{controls.adsEnabled ? <div className="mt-10 border border-dashed border-white/15 p-6"><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/30">Advertisement</p><p className="mt-4 font-serif text-xl text-white/60">A calm space for a privacy-respecting cinema partner.</p><p className="mt-2 text-sm leading-6 text-white/30">No pop-ups, forced redirects, or misleading download buttons.</p></div> : null}</div></section>
  </main>;
}

function Detail({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="grid grid-cols-[24px_1fr_auto] items-center gap-3 py-4 text-sm"><span className="text-[#ef796d]">{icon}</span><dt className="text-white/40">{label}</dt><dd>{value}</dd></div>; }
