'use client';
import { Plus, Trash2 } from 'lucide-react';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import type { AdminMovie } from '../../db';
type Episode = NonNullable<AdminMovie['episodes']>[number];
export function EpisodeBuilder({ episodes, onChange }: { episodes: Episode[]; onChange: (episodes: Episode[]) => void }) {
  function update(index: number, key: keyof Episode, value: string) { onChange(episodes.map((episode, itemIndex) => itemIndex === index ? { ...episode, [key]: key === 'season' || key === 'episode' ? Math.max(1, Number(value) || 1) : value } : episode)); }
  return <div className="space-y-3">{episodes.map((episode, index) => <div key={`${index}-${episode.season}-${episode.episode}`} className="grid gap-3 rounded-xl border border-white/10 bg-black/10 p-4 md:grid-cols-[110px_110px_1fr_1fr_auto]"><label><span className="mb-1 block text-xs text-white/40">Season</span><Input type="number" min={1} value={episode.season} onChange={(event) => update(index, 'season', event.target.value)}/></label><label><span className="mb-1 block text-xs text-white/40">Episode</span><Input type="number" min={1} value={episode.episode} onChange={(event) => update(index, 'episode', event.target.value)}/></label><label><span className="mb-1 block text-xs text-white/40">Title</span><Input value={episode.title} onChange={(event) => update(index, 'title', event.target.value)} placeholder="Episode title"/></label><label><span className="mb-1 block text-xs text-white/40">Stream link</span><Input value={episode.url ?? ''} onChange={(event) => update(index, 'url', event.target.value)} placeholder="https://..."/></label><Button type="button" variant="ghost" className="self-end text-red-300" onClick={() => onChange(episodes.filter((_, itemIndex) => itemIndex !== index))} aria-label={`Remove episode ${episode.season}-${episode.episode}`}><Trash2/></Button></div>)}<Button type="button" variant="outline" onClick={() => onChange([...episodes, { season: 1, episode: episodes.length + 1, title: '', url: undefined }])}><Plus/> Add episode</Button><p className="text-xs text-white/40">Thumbnail and overview use the movie poster and description already stored in the current database model. Episode stream links use the existing episode URL field; standalone download options remain available from the movie record.</p></div>;
}
